version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: root
